"""empty message

Revision ID: 04636aea9440
Revises: 14c462e99a28
Create Date: 2021-09-29 11:06:48.747219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04636aea9440'
down_revision = '14c462e99a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'picture')
    # ### end Alembic commands ###
