"""empty message

Revision ID: 27433bee740f
Revises: 2ba913e74320
Create Date: 2021-10-20 18:17:53.092540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27433bee740f'
down_revision = '2ba913e74320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_image')
    op.drop_column('projects', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('picture', sa.VARCHAR(), nullable=True))
    op.add_column('projects', sa.Column('project_image', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
