"""empty message

Revision ID: 2ba913e74320
Revises: 682e1607aa5b
Create Date: 2021-10-20 18:15:42.309878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba913e74320'
down_revision = '682e1607aa5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('demo', sa.Text(), nullable=True))
    op.drop_column('projects', 'picture')
    op.drop_column('projects', 'project_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_image', sa.VARCHAR(), nullable=True))
    op.add_column('projects', sa.Column('picture', sa.VARCHAR(), nullable=True))
    op.drop_column('projects', 'demo')
    # ### end Alembic commands ###
