"""empty message

Revision ID: 630e94f464d4
Revises: 0c5f1e8233f8
Create Date: 2021-09-16 16:44:19.811007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630e94f464d4'
down_revision = '0c5f1e8233f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('link', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'link')
    # ### end Alembic commands ###
