"""empty message

Revision ID: 682e1607aa5b
Revises: 04636aea9440
Create Date: 2021-09-29 12:29:22.224238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682e1607aa5b'
down_revision = '04636aea9440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_image', sa.String(), nullable=True))
    op.drop_column('projects', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('picture', sa.VARCHAR(), nullable=True))
    op.drop_column('projects', 'project_image')
    # ### end Alembic commands ###
